name: 12 Factor Digit Classifier

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest black
        
    - name: Run code formatter (black) check
      run: |
          black --check .
          
    - name: Test with pytest
      env:
       MODEL_PATH: "model/model.pth"
       LOG_PATH: "logs/"
      run: |
        pytest tests/
        
    - name: Build Docker Image
      run: docker build -t 12-factor-digit-classifier .
